### ISSUE TITLE
Fix endpoint handling when path is included

### ISSUE THREAD

**Issue by arax** [EGI-FCTF/rOCCI-api#19]
When the `endpoint` URL contains a path element (e.g., `http://localhost:3000/path`), it breaks HTTP request construction.
~~~
<- "GET /occi1.1/compute/ HTTP/1.1\r\nAccept: text/uri-list\r\nUser-Agent: rOCCI-core/4.3.2 rOCCI-api/4.3.1 OCCI/1.1 ruby-x86_64-linux/1.9.3p484\r\nX-Auth-Token: 0e14c066d02c\r\nConnection: close\r\nHost: localhost:8774\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "Content-Type: text/uri-list; charset=utf8\r\n"
-> "Content-Length: 74\r\n"
-> "Server: ooi/0.0.0 OCCI/1.1\r\n"
-> "X-Compute-Request-Id: req-5d40ddd3-765b-4954-86d0-52448fe5c9f0\r\n"
-> "Date: Wed, 27 May 2015 07:22:03 GMT\r\n"
-> "Connection: close\r\n"
-> "\r\n"
reading 74 bytes...
-> "http://localhost:8774/occi1.1/compute/52ff167e-2186-4099-85b9-6a832021bb2d"

<- "GET /occi1.1/occi1.1/compute/52ff167e-2186-4099-85b9-6a832021bb2d HTTP/1.1\r\nAccept: text/plain,text/occi\r\nUser-Agent: rOCCI-core/4.3.2 rOCCI-api/4.3.1 OCCI/1.1 ruby-x86_64-linux/1.9.3p484\r\nX-Auth-Token: 0e14ce66d02c\r\nConnection: close\r\nHost: localhost:8774\r\n\r\n"
-> "HTTP/1.1 404 Not Found\r\n"
-> "Server: ooi/0.0.0 OCCI/1.1\r\n"
-> "Content-Type: text/plain; charset=UTF-8\r\n"
-> "Content-Length: 32\r\n"
-> "X-Compute-Request-Id: req-b2b7bf35-6ffe-4813-9a4a-86de92ebe137\r\n"
-> "Date: Wed, 27 May 2015 07:22:03 GMT\r\n"
-> "Connection: close\r\n"
-> "\r\n"
reading 32 bytes...
-> "The resource could not be found."
~~~

**Comment by alvarolopez** [comment]
Hi Boris,

do you have an estimate on when this issue would be solved?

**Comment by arax** [comment]
I'm trying to hunt down the root cause of this issue. It's not exactly easy since all paths are determined dynamically. I should be able to have it fixed by the end of the week.

**Comment by arax** [comment]
@alvarolopez @enolfc 
Do you have a private instance I could use for testing? (=> private e-mail)
If not, could you, please, send me a dump of your OCCI model? (`GET /-/`)

Thanks!

**Comment by arax** [comment]
Could you, please, test this change?

First, make sure you are running an up-to-date version of rOCCI-cli:
```bash
$ occi -d -v
CLI:  4.3.1
API:  4.3.1
Core: 4.3.2
```
Then find the following file and make a copy:
```
lib/occi/api/client/client_http.rb
```
After that replace it with:
```
https://raw.githubusercontent.com/arax/rOCCI-api/703adc90576d4243a9774cb76b6cd8f59eb09280/lib/occi/api/client/client_http.rb
```

Depending on how you installed rOCCI-cli, the `client_http.rb` file will be either somewhere under `/opt` (native package) or deep in your system's ruby libraries (gem). Let me know if you encounter any problems.

**Comment by enolfc** [comment]
I have tested the change but unfortunately, our model seems broken too. We are publishing: 

compute;scheme="http://schemas.ogf.org/occi/infrastructure#";class="kind";title="compute resource";rel="http://schemas.ogf.org/occi/core#resource";location="/compute/"

So now occi is trying /compute instead of /occi1.1/compute:

<- "GET /compute/ HTTP/1.1\r\nAccept: text/uri-list\r\nUser-Agent: rOCCI-core/4.3.2 rOCCI-api/4.3.1 OCCI/1.1 ruby-x86_64-linux/1.9.3p484\r\nX-Auth-Token: XX\r\nConnection: close\r\nHost: localhost:8774\r\n\r\n"

will fix the compute location and try again.

**Comment by enolfc** [comment]
Hi Boris,

publishing location="/occi1.1/compute" in the model works, however using a relative location="compute/" fails with this error:

F, [2015-06-16T07:52:29.547569 #4703] FATAL -- : [rOCCI-cli] An error occurred! Message: the scheme http does not accept registry part: localhost:8774compute (or bad hostname?)
/usr/lib/ruby/1.9.1/uri/generic.rb:213:in `initialize': the scheme http does not accept registry part: localhost:8774compute (or bad hostname?) (URI::InvalidURIError)

should this be accepted too?

**Comment by arax** [comment]
AFAIK this is not mentioned in the standard ... but I would vote against accepting relative (path) locations. It creates too much ambiguity, especially for the client. The only thing I could do to make this work is prefix each location with `/` by default ... and that's a bit pointless.
